name: Android CI

on:
  push:
    branches: [ "working-selinuxns" ]
  pull_request:
    branches: [ "working-selinuxns" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 打包代码为 tar.gz
      - name: Package code
        run: tar -czvf test.tar.gz ./
          
      # 3. 上传构建产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-code-package  # 产物名称
          path: test.tar.gz # 要上传的文件路径
          retention-days: 7          # 产物保留天数（默认90天，这里设为7天节省空间）
